### PR TITLE
Virtual directory bugfix

### PR DESCRIPTION
**Pull request by hholle**
Bugfix regarding virtual directories. Without the fix the authentication
redirect would generate a 404

### CODE REVIEW

**Comment by pysco68** [comment]
Thank you for the pull request. I'll try to release this asap. Could you eventually provide me with a test-case where this was originally failing?

N.B.: I'll be afk for the next three weeks approx. so it'll take some time 'till I release it. Sorry

**Comment by pysco68** [comment]
Hello Hendrik, I just had time to look at this again. And I'd like to understand what you actually did there, or in which setup the currently released code was failing. Please provide me some additional information.

Thank you very much!

**Comment by hholle** [comment]
Hey Yannic,

please ignore my commit. I messed up. sorry

thanks for your work.

regards

henrik

2015-06-14 15:38 GMT+02:00 Yannic Staudt <notifications@github.com>:

**Comment by pysco68** [comment]
Okay, thanks for your answer.

**Pull request closed without merging**
