### PR TITLE
Added the ability to override the default claims

### PR DESCRIPTION
**Pull request by martinjt**
Needed this in order to get the Full sAMAccountName.  Makes it a bit more versatile as well.

Let me know if you're not going to publish and we'll build it internally instead.

### CODE REVIEW

**Comment by pysco68** [comment]
Hello Martin, I'll review this today, thank you for the PR in the meanwhile

Note: if I don't find any major issue with your contribution I'll package it!

**Comment by martinjt** [comment]
I actually have an addition to this, need to pass the options to the
handler too.

**Comment by martinjt** [comment]
I've pushed the changes, I'll need to make a decision on Monday as to whether we use an internal version or not, so if you could let me know by then that would be great.

**Comment by pysco68** [comment]
I'll push the updated nuget package in a minute or so. Thank you for the contribution

**Comment by pysco68** [comment]
Note: it's there: v1.0.3 (https://www.nuget.org/packages/Pysco68.Owin.Authentication.Ntlm/1.0.3)

You'll may have to wait a few minutes to have Nuget.org index it

**Pull request merged**
